#!/usr/bin/env bash

nix-env -f packages.nix -i -j 20

## install telegram that works with my environment
nix-build telegram.nix --out-link install-telegram
echo "run install-telegram if needed."

nix-shell get-slack-deb.nix --run copy-slack-deb
nix-shell get-vscode-deb.nix --run copy-vscode-deb
nix-shell get-mpv-deb.nix --run copy-mpv-deb
